#!/bin/bash

#####################################
# constant terms

remotearchive=rband003@hammer.cs.ucr.edu:/home/csmajs/rband003/Projects/
localarchive=~/Projects/
grindspath=~/Projects/thegrind/.grinds

#####################################
# Function definitions

function lock () {
	tar -czf ${1}.tgz $1
	gpg --output ${1}.tgz.enc --symmetric --cipher-algo AES256 ${1}.tgz
	rm -rf ${1}.tgz
}

function unlock () {
	basefilename=$(echo ${1} | awk -F. '{print $1}')
	gpg --output ${basefilename}.tgz --decrypt ${basefilename}.tgz.enc
	tar -xzf ${basefilename}.tgz -C $localarchive
	rm -rf ${basefilename}.tgz
}

function push () {
	lock $1
	scp ${1}.tgz.enc $remotearchive
	rm ${1}.tgz.enc
	((grep "$sample_dir" $grindspath) && (echo repo exists... updating)) || (echo "${sample_dir}.tgz.enc" >> $grindspath)
}

function pull () {
	scp ${remotearchive}${1} $localarchive
	unlock ${localarchive}${1}
	rm ${localarchive}${1}
}

#####################################
# main code

if [[ $1 == "lock" ]]; then
	lock $2
elif [[ $1 == "unlock" ]]; then
	unlock $2
elif [[ $1 == "push" ]]; then
	push $2
elif [[ $1 == "pull" ]]; then
	if [[ $# -ne 2 ]]; then
		cat $grindspath
	else
		pull $2
	fi
else
	echo "Incorrect usage of grind"
fi
